package com.dailylog.entity;

// Generated 2013-10-17 15:38:10 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LogInfo generated by hbm2java
 */
public class LogInfo implements java.io.Serializable {

	private Long id;
	private User user;
	private String log;
	private Date logTime;
	private Integer colorTag;
	private Date createdTime;

	public LogInfo() {
	}

	public LogInfo(User user, String log, Date logTime) {
		this.user = user;
		this.log = log;
		this.logTime = logTime;
	}

	public LogInfo(User user, String log, Date logTime, Integer colorTag, Date createdTime) {
		this.user = user;
		this.log = log;
		this.logTime = logTime;
		this.colorTag = colorTag;
		this.createdTime = createdTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	public Integer getColorTag() {
		return this.colorTag;
	}

	public void setColorTag(Integer colorTag) {
		this.colorTag = colorTag;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
